"""
NotepediaX Engine — Pydantic Data Contracts (Schemas)
======================================================
Phase 1, 2 & 3: All request/response contracts:
- Student Onboarding & Profiles
- Diagnostic Assessment
- 8 Granular Universal Learning Event Types
- Feature Vectors & Retention/Revision Due
- Candidate Activities & Scored Recommendations (Phase 3)
- Constraint-Based Scheduled Activities, Daily Plans & Feedback (Phase 3)
"""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================

class EventType(str, Enum):
    """All 8 event types supported by the NotepediaX event stream."""
    QUESTION_ATTEMPT = "QUESTION_ATTEMPT"
    NOTE_READ = "NOTE_READ"
    QUIZ_COMPLETE = "QUIZ_COMPLETE"
    VIDEO_COMPLETE = "VIDEO_COMPLETE"
    FLASHCARD_REVIEW = "FLASHCARD_REVIEW"
    DOUBT_ASKED = "DOUBT_ASKED"
    PLAN_COMPLETED = "PLAN_COMPLETED"
    PLAN_SKIPPED = "PLAN_SKIPPED"


class ActivityType(str, Enum):
    """Activity types generated by candidate generator and scheduler."""
    NOTE_READ = "NOTE_READ"
    VIDEO_LESSON = "VIDEO_LESSON"
    QUIZ_ATTEMPT = "QUIZ_ATTEMPT"
    FLASHCARD_REVIEW = "FLASHCARD_REVIEW"
    SPACED_REVISION = "SPACED_REVISION"
    MISTAKE_REVIEW = "MISTAKE_REVIEW"
    BREAK = "BREAK"


class ActivityStatus(str, Enum):
    """Execution status of scheduled activities."""
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"


class DifficultyFeedback(str, Enum):
    """Student feedback regarding activity difficulty."""
    TOO_EASY = "TOO_EASY"
    TOO_HARD = "TOO_HARD"
    APPROPRIATE = "APPROPRIATE"


class RelevanceFeedback(str, Enum):
    """Student feedback regarding activity relevance/helpfulness."""
    HELPFUL = "HELPFUL"
    NOT_HELPFUL = "NOT_HELPFUL"


# =============================================================================
# Student Profile
# =============================================================================

class StudentProfileCreate(BaseModel):
    """Payload accepted during student onboarding."""
    academic_level: str = Field(
        ...,
        examples=["class_11"],
        description="Current academic level of the student.",
    )
    exam_target: str = Field(
        ...,
        examples=["JEE_MAIN"],
        description="Primary exam the student is preparing for.",
    )
    target_score: int = Field(
        default=0,
        ge=0,
        description="Aspirational score target (exam-specific scale).",
    )
    daily_available_minutes: int = Field(
        default=60,
        ge=10,
        le=720,
        description="Minutes the student can dedicate to study each day.",
    )
    preferred_language: str = Field(
        default="en",
        examples=["en", "hi"],
        description="ISO 639-1 language code.",
    )


class StudentProfileResponse(BaseModel):
    """Shape returned after successful onboarding."""
    id: UUID
    academic_level: str
    exam_target: str
    target_score: int
    daily_available_minutes: int
    preferred_language: str
    created_at: datetime


# =============================================================================
# Diagnostic Submission
# =============================================================================

class DiagnosticSubmission(BaseModel):
    """
    Topic-level diagnostic test scores submitted after the student
    completes an initial assessment.
    """
    scores: dict[str, float] = Field(
        ...,
        examples=[{"physics_electrostatics_ef": 0.65, "chemistry_mole_concept": 0.40}],
        description="Mapping of topic_id → normalised diagnostic score (0–1).",
    )


# =============================================================================
# Phase 2 — Granular Event Metadata Models (8 types)
# =============================================================================

class QuestionAttemptMeta(BaseModel):
    """Metadata for a single question attempt."""
    question_id: str = Field(..., description="Unique question identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    difficulty: float = Field(..., ge=0.0, le=1.0, description="Question difficulty (0–1).")
    correct: bool = Field(..., description="Whether the answer was correct.")
    response_time_seconds: int = Field(..., ge=0, description="Time taken in seconds.")
    attempt_number: int = Field(default=1, ge=1, description="Attempt count for this question.")


class NoteReadMeta(BaseModel):
    """Metadata for a note reading session."""
    note_id: str = Field(..., description="Unique note identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    dwell_time_seconds: int = Field(..., ge=0, description="Total time spent reading (seconds).")
    completion_percentage: float = Field(
        ..., ge=0.0, le=100.0,
        description="Percentage of note content consumed (0–100).",
    )


class QuizCompleteMeta(BaseModel):
    """Metadata for a completed quiz."""
    quiz_id: str = Field(..., description="Unique quiz identifier.")
    topic_ids: list[str] = Field(..., min_length=1, description="Topics covered in the quiz.")
    total_questions: int = Field(..., ge=1, description="Number of questions in the quiz.")
    score_percentage: float = Field(
        ..., ge=0.0, le=100.0,
        description="Final quiz score as a percentage (0–100).",
    )


class VideoCompleteMeta(BaseModel):
    """Metadata for a video watch session."""
    video_id: str = Field(..., description="Unique video identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    duration_watched_seconds: int = Field(..., ge=0, description="Seconds of video watched.")
    completion_rate: float = Field(
        ..., ge=0.0, le=1.0,
        description="Fraction of video watched (0–1).",
    )


class FlashcardReviewMeta(BaseModel):
    """Metadata for a single flashcard review."""
    card_id: str = Field(..., description="Unique flashcard identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    recalled_correctly: bool = Field(..., description="Whether the student recalled the card.")
    confidence_rating: int = Field(
        ..., ge=1, le=5,
        description="Self-reported confidence (1 = no idea, 5 = certain).",
    )


class DoubtAskedMeta(BaseModel):
    """Metadata for a doubt/question raised by the student."""
    doubt_id: str = Field(..., description="Unique doubt identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    question_text: str = Field(..., min_length=1, description="The doubt question text.")


class PlanCompletedMeta(BaseModel):
    """Metadata for a completed study plan activity."""
    activity_id: str = Field(..., description="Unique activity identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    reason: str | None = Field(default=None, description="Optional completion notes.")


class PlanSkippedMeta(BaseModel):
    """Metadata for a skipped study plan activity."""
    activity_id: str = Field(..., description="Unique activity identifier.")
    topic_id: str = Field(..., description="Canonical topic ID.")
    reason: str | None = Field(default=None, description="Optional reason for skipping.")


# ---------------------------------------------------------------------------
# Metadata model registry
# ---------------------------------------------------------------------------
EVENT_META_REGISTRY: dict[EventType, type[BaseModel]] = {
    EventType.QUESTION_ATTEMPT: QuestionAttemptMeta,
    EventType.NOTE_READ: NoteReadMeta,
    EventType.QUIZ_COMPLETE: QuizCompleteMeta,
    EventType.VIDEO_COMPLETE: VideoCompleteMeta,
    EventType.FLASHCARD_REVIEW: FlashcardReviewMeta,
    EventType.DOUBT_ASKED: DoubtAskedMeta,
    EventType.PLAN_COMPLETED: PlanCompletedMeta,
    EventType.PLAN_SKIPPED: PlanSkippedMeta,
}


# =============================================================================
# Universal Learning Event
# =============================================================================

class UniversalLearningEvent(BaseModel):
    """
    Canonical event contract that every NotepediaX module emits.
    """
    student_id: UUID
    event_type: EventType
    topic_id: str = Field(
        ...,
        examples=["physics_electrostatics_ef"],
        description="Canonical topic ID from the taxonomy.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=__import__("datetime").timezone.utc),
        description="ISO-8601 timestamp of when the event occurred.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Event-type-specific payload.",
    )


# =============================================================================
# Learner State & Features Responses
# =============================================================================

class LearnerStateResponse(BaseModel):
    """Read-only view of the student's dynamic knowledge state."""
    student_id: UUID
    topic_mastery: dict[str, Any] = Field(
        default_factory=dict,
        description="topic_id → mastery float (0–1).",
    )
    retention_scores: dict[str, Any] = Field(
        default_factory=dict,
        description="topic_id → {score, last_seen, revision_priority}.",
    )
    last_updated_at: datetime | None = None


class FeatureVectorResponse(BaseModel):
    """Compiled ML feature vector for a student × topic pair."""
    student_id: str
    topic_id: str
    rolling_accuracy: float = Field(description="7-day rolling accuracy (0–1).")
    avg_response_time: float = Field(description="Average response time (seconds).")
    study_consistency: float = Field(description="Active-day ratio over window (0–1).")
    total_attempts: int = Field(description="Total question attempts in window.")
    current_mastery: float = Field(description="Current topic mastery (0–1).")
    retention_score: float = Field(description="Current retention score (0–1).")
    revision_priority: float = Field(description="1 − retention_score.")


class RevisionDueItem(BaseModel):
    """A single topic that is due for revision."""
    topic_id: str
    retention_score: float
    revision_priority: float
    days_since_last_seen: float


class RevisionDueResponse(BaseModel):
    """List of topics below the retention threshold, sorted by urgency."""
    student_id: str
    threshold: float
    topics_due: list[RevisionDueItem]


# =============================================================================
# Phase 3 — Recommendation & Planning Models
# =============================================================================

class CandidateActivity(BaseModel):
    """A candidate learning activity generated by the candidate generator."""
    activity_id: str = Field(..., description="Unique generated ID for the candidate activity.")
    topic_id: str = Field(..., description="Target topic ID from topic_taxonomy.")
    title: str = Field(default="", description="Descriptive title of the activity.")
    activity_type: ActivityType = Field(..., description="Type of learning interaction.")
    estimated_duration_minutes: int = Field(..., ge=1, le=180, description="Estimated duration in minutes.")
    difficulty: float = Field(default=0.5, ge=0.0, le=1.0, description="Relative difficulty score (0.0–1.0).")


class ScoredRecommendation(CandidateActivity):
    """Candidate activity scored and ranked by the recommendation engine."""
    final_score: float = Field(..., ge=0.0, le=1.0, description="Aggregate recommendation score (0–1).")
    scoring_breakdown: dict[str, float] = Field(
        default_factory=dict,
        description="Individual factor scores (knowledge_gap, exam_priority, etc.).",
    )
    recommendation_reason: str = Field(
        ...,
        description="Explainable reasoning string for display in UI.",
    )


class ScheduledActivity(BaseModel):
    """A single scheduled block within a daily learning plan."""
    activity_id: str = Field(..., description="Identifier matching activity or break.")
    time_slot: str = Field(..., description="e.g. '18:00-18:30' or 'Slot 1 (0–30 min)'.")
    activity: ScoredRecommendation | None = Field(
        default=None,
        description="The scored activity (None if is_break is True).",
    )
    is_break: bool = Field(default=False, description="True if this is an automatically inserted rest break.")
    duration_minutes: int = Field(default=30, ge=5, le=180, description="Allocated block duration in minutes.")
    status: ActivityStatus = Field(default=ActivityStatus.PENDING, description="Execution status.")


class DailyPlan(BaseModel):
    """A personalized, constraint-bounded daily study plan."""
    plan_id: UUID = Field(..., description="Unique identifier for the generated plan.")
    student_id: UUID = Field(..., description="Target student UUID.")
    plan_date: date = Field(..., description="Date for which the plan is scheduled.")
    total_allocated_minutes: int = Field(..., description="Total minutes including study & breaks.")
    activities: list[ScheduledActivity] = Field(default_factory=list, description="Ordered schedule of activities.")
    completion_status: float = Field(default=0.0, ge=0.0, le=1.0, description="Fraction of activities completed.")
    status: str = Field(default="active", description="active | completed | updated")


class PlanFeedback(BaseModel):
    """Feedback submitted by a student or client on a scheduled activity."""
    activity_id: str = Field(..., description="ID of the activity being updated.")
    status: ActivityStatus = Field(..., description="COMPLETED | SKIPPED | PARTIALLY_COMPLETED")
    difficulty_feedback: DifficultyFeedback | None = Field(
        default=None,
        description="Subjective difficulty rating.",
    )
    relevance_feedback: RelevanceFeedback | None = Field(
        default=None,
        description="Subjective relevance rating.",
    )
    performance_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Optional quiz or assessment score (0-1).",
    )
    actual_duration_minutes: int | None = Field(
        default=None,
        ge=1,
        description="Actual time spent on the activity.",
    )


class OptimizePlanRequest(BaseModel):
    """Request payload for triggering daily plan optimization."""
    plan_date: date | None = Field(default=None, description="Plan date (defaults to today).")
    available_minutes: int | None = Field(
        default=None,
        ge=15,
        le=720,
        description="Optional override for daily available minutes.",
    )
    focus_topics: list[str] | None = Field(
        default=None,
        description="Optional list of topic IDs to prioritize.",
    )


# =============================================================================
# Generic API Response Wrapper
# =============================================================================

class APIResponse(BaseModel):
    """Standard envelope for all API responses."""
    success: bool = True
    message: str = ""
    data: Any = None
